USE [master]
GO

-- Set database to SINGLE_USER mode to force disconnect all users
ALTER DATABASE ISSDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO

DROP DATABASE [ISSDB]

/****** Object:  Database [ISSDB]    Script Date: 3/19/2025 10:42:59 PM ******/
CREATE DATABASE [ISSDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ISSDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\ISSDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ISSDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\ISSDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ISSDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ISSDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ISSDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ISSDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ISSDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ISSDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ISSDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ISSDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ISSDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ISSDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ISSDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ISSDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ISSDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ISSDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ISSDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ISSDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ISSDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ISSDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ISSDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ISSDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ISSDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ISSDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ISSDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ISSDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ISSDB] SET  MULTI_USER 
GO

ALTER DATABASE [ISSDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ISSDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ISSDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ISSDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ISSDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ISSDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ISSDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [ISSDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [ISSDB] SET  READ_WRITE 
GO

-- Database initial tables

USE [ISSDB]
GO

CREATE TABLE [dbo].[Users](
	[Id] BIGINT PRIMARY KEY CLUSTERED IDENTITY(1,1),
	[UserName] [nvarchar](256) UNIQUE NOT NULL,
	[Email] [nvarchar](256) UNIQUE NOT NULL,
	[PasswordHash] [nvarchar](max) NOT NULL,
	[Image] [nvarchar](max)
)

CREATE TABLE [dbo].[Groups](
	[Id] BIGINT PRIMARY KEY CLUSTERED IDENTITY(1,1),
	[Name] [nvarchar](55) UNIQUE NOT NULL,
	[Image] [nvarchar](max),
	[Description] [nvarchar](250),
	[AdminId] BIGINT NOT NULL REFERENCES [Users]([Id])
)

CREATE TABLE [dbo].[Posts](
	[Id] BIGINT PRIMARY KEY CLUSTERED IDENTITY(1,1),
	[Title] [nvarchar](55) NOT NULL,
	[Content] [nvarchar](max) NULL,
	[CreatedDate] DATETIME NOT NULL,
	[UserId] BIGINT NOT NULL REFERENCES [Users](Id),
	[PostVisibility] INT NOT NULL, 
	[GroupId] BIGINT REFERENCES [Groups](Id),
	[PostTag] INT NULL,

	CONSTRAINT CHK_Post_Visibility CHECK ((PostVisibility = 4 AND GroupId IS NOT NULL) OR (PostVisibility <> 4 AND GroupId IS NULL) )
)

CREATE TABLE [dbo].[Reactions](
	[UserId] BIGINT NOT NULL REFERENCES [Users]([Id]),
	[PostId] BIGINT NOT NULL REFERENCES [Posts]([Id]),
	[ReactionType] INT NOT NULL

	PRIMARY KEY CLUSTERED ([UserId],[PostId]) 
)

CREATE TABLE [dbo].[Comments](
	[Id] BIGINT PRIMARY KEY CLUSTERED IDENTITY(1,1),
	[UserId] BIGINT NOT NULL REFERENCES[Users]([Id]),
	[PostId] BIGINT NOT NULL REFERENCES[Posts]([Id]),
	[Content] [nvarchar](250) NOT NULL,
	[CreatedDate] DATETIME NOT NULL
)

CREATE TABLE [dbo].[GroupUsers](
	[UserId] BIGINT NOT NULL REFERENCES[Users]([Id]),
	[GroupId] BIGINT NOT NULL REFERENCES[Groups]([Id]),
	PRIMARY KEY CLUSTERED ([UserId],[GroupId]) 
)

CREATE TABLE [dbo].[UserFollowers](
	[UserId] BIGINT NOT NULL REFERENCES[Users]([Id]),
	[FollowerId] BIGINT NOT NULL REFERENCES[Users]([Id]),
	PRIMARY KEY CLUSTERED ([UserId],[FollowerId]),
	CHECK (UserId <> FollowerId)
)
